### ISSUE TITLE
Unable to use tls on helm install

### ISSUE THREAD

**Issue by wofish2** [WASdev/microservicebuilder.lib#70]
ICP forces using tls to Helm commands.

"Important: After you configure a connection, you must add the --tls option to Helm commands that access the server through Tiller."

https://www.ibm.com/support/knowledgecenter/en/SSBS6K_2.1.0.2/app_center/create_helm_cli.html

I am trying to customize the microservicebuilder.lib (add --tls to helm install command), but I got the following error during microservicebuilder-pipeline build:

```
 container ('helm') {
            sh "/helm init --client-only --skip-refresh"

            def deployCommand = "/helm install ${realChartFolder} --wait --tls --set test=true --values pipeline.yaml --namespace ${testNamespace} --name ${tempHelmRelease}"

            if (fileExists("chart/overrides.yaml")) {

              deployCommand += " --values chart/overrides.yaml"

            }

            sh deployCommand

          }
```

```
+ /helm install --tls chart/capsmaltapp --wait --set test=true --values pipeline.yaml --namespace testns-1-9103619c-037d-46aa-8f82-375712e0d0b5 --name capsmaltapp-testns-1-9103619c-037d-46aa-8f82-375712e0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x88b16b]

goroutine 1 [running]:
k8s.io/helm/pkg/tlsutil.ClientConfig(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0, 0x10, 0xc42025ff80, ...)
	/root/hchen/gopath/src/k8s.io/helm/pkg/tlsutil/cfg.go:59 +0xeb
main.newClient(0xc4202680a8, 0xc42025ff80)
	/root/hchen/gopath/src/k8s.io/helm/cmd/helm/helm.go:270 +0x129
main.ensureHelmClient(0x0, 0x0, 0x7fff1d92059c, 0x11)
	/root/hchen/gopath/src/k8s.io/helm/cmd/helm/helm.go:258 +0x45
main.newInstallCmd.func1(0xc420388900, 0xc420091550, 0x1, 0xb, 0x0, 0x0)
	/root/hchen/gopath/src/k8s.io/helm/cmd/helm/install.go:172 +0x285
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).execute(0xc420388900, 0xc4200914a0, 0xb, 0xb, 0xc420388900, 0xc4200914a0)
	/root/hchen/gopath/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:599 +0x3e9
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4203f0480, 0xc420326b40, 0xc4202eafc0, 0xc4202de000)
	/root/hchen/gopath/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:689 +0x339
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4203f0480, 0xc, 0xc)
	/root/hchen/gopath/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
	/root/hchen/gopath/src/k8s.io/helm/cmd/helm/helm.go:154 +0x77
```

**Comment by davidcurrie** [comment]
@wofish2 - Microservice Builder is deprecated and there are no plans to support it in ICP 2.1.0.2+. It has been superseded by the pipeline capability in [Microclimate](http://ibm.biz/microclimate). Currently Microclimate deploys its own Tiller but when ICP supports the use of the community Helm client again we will expose the TLS options and use the ICP Tiller again.
